version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 18
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket peech-demo-bucket-1 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml