AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
  # Details about the myDateTimeFunction Lambda function
  myDateTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: myDateTimeFunction.handler
      Runtime: nodejs18.x
      Timeout: 60 # optional, but recommended
      MemorySize: 128 # optional, but recommended
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: '*'
      DeploymentPreference:
        Type: AllAtOnce